site_name: Rye PyCharm Plugin
site_description: A JetBrains PyCharm plugin for rye.

theme:
    name: 'material'
    palette:
      primary: 'light blue'
      accent: 'light blue'
    analytics:
      gtag: 275257853
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: 🔗

repo_name: koxudaxi/rye-pycharm-plugin
repo_url: https://github.com/koxudaxi/rye-pycharm-plugin
site_url: https://koxudaxi.github.io/rye-pycharm-plugin

nav:
    - Overview: index.md
    - Install: install.md
    - Development: development.md
    - Changelog: CHANGELOG.md
plugins:
  - search